### ISSUE TITLE
ghc 8.4.1 support

### ISSUE THREAD

**Issue by peti** [vimus/libmpd-haskell#105]
libmpd-0.9.0.7 does not compile with ghc 8.4.1:

~~~
src/Network/MPD/Commands/Query.hs:41:10: error:
    • No instance for (Semigroup Query)
        arising from the superclasses of an instance declaration
    • In the instance declaration for ‘Monoid Query’
   |
41 | instance Monoid Query where
   |          ^^^^^^^^^^^^
~~~

**Comment by joachifm** [comment]
Thank you for the report. I've uploaded a new version to Hackage.
