### ISSUE TITLE
GHC 8.6.1 support

### ISSUE THREAD

**Issue by jereksel** [vimus/libmpd-haskell#106]
Master branch doesn't build on ghc 8.6.1 (tested with stack on resolver `nightly-2018-10-04`):

```
/XXX/libmpd-haskell/src/Network/MPD/Core.hs:120:13: error:
    • No instance for (Control.Monad.Fail.MonadFail MPD)
        arising from a do statement
        with the failable pattern ‘[msg]’
    • In a stmt of a 'do' block: [msg] <- send ""
      In the expression:    
        do [msg] <- send "" 
           if "OK MPD" `isPrefixOf` msg then
               MPD $ checkVersion $ parseVersion msg
           else             
               return False 
      In an equation for ‘checkConn’:
          checkConn         
            = do [msg] <- send ""
                 if "OK MPD" `isPrefixOf` msg then
                     MPD $ checkVersion $ parseVersion msg
                 else       
                     return False
    |                       
120 |             [msg] <- send ""
    | 
```
