### ISSUE TITLE
tests/Arbitrary.hs: error: Overlapping instances for Arbitrary (M.Map Metadata [Value])

### ISSUE THREAD

**Issue by juhp** [vimus/libmpd-haskell#93]
While trying to build libmpd in Stackage Nightly, the testsuite failed to build with ghc-8.0.1:

```
tests/Arbitrary.hs:121:26: error:
    • Overlapping instances for Arbitrary (M.Map Metadata [Value])
        arising from a use of ‘arbitrary’
      Matching instances:
        instance [safe] (Ord k, Arbitrary k, Arbitrary v) =>
                        Arbitrary (M.Map k v)
          -- Defined in ‘Test.QuickCheck.Arbitrary’
        instance Arbitrary (M.Map Metadata [Value])
          -- Defined at tests/Arbitrary.hs:54:10
    • In the second argument of ‘(<*>)’, namely ‘arbitrary’
      In the first argument of ‘(<*>)’, namely
        ‘Song <$> arbitrary <*> arbitrary’
      In the first argument of ‘(<*>)’, namely
        ‘Song <$> arbitrary <*> arbitrary <*> possibly arbitrary’
```

**Comment by juhp** [comment]
This can be reproduced with:

```
$ cabal unpack libmpd-0.9.0.5
$ cd libmpd-0.9.0.5
$ stack init --resolver nightly
$ stack test
```

if you have ghc-8.0.1 installed (otherwise you can add `--install-ghc`).

**Comment by joachifm** [comment]
Thank you for the report, I'll look into this shortly.

**Comment by joachifm** [comment]
I have uploaded a new point release to hackage.

**Comment by juhp** [comment]
Thanks - haven't tested yet.
